### ISSUE TITLE
Error with offset for Tilemap

### ISSUE THREAD

**Issue by anatagawa** [flozz/img2gb#2]
Salut, 

J'utilise la commande suivante pour essayé de placer mon tilemap a la position 95 avec l'offset de img2gb

`img2gb.exe tilemap --output-c-file=../src/ui_tilemap.c --output-header-file=../src/ui_tilemap.h --offset=95 --name WINDOW_TILEMAP window_tileset.png ui_tilemap.png`

et j'obtiens cette erreur :

---
- Traceback (most recent call last):
-   File "i2gb.py", line 40, in <module>
-   File "i2gb.py", line 35, in main
-   File "img2gb\__init__.py", line 187, in generate_tilemap
- NotImplementedError
- [16208] Failed to execute script i2gb
---

Je ne sais pas du tout quoi faire pour que cela fonctionne :(

**Comment by flozz** [comment]
Bonjour,

Vous ne pourrez pas faire marcher cette option pour le moment (désolé).

Je ne l'avait pas encore implémentée par manque de temps, et je l'avais un peu oublié depuis... Je vais m'y remettre rapidement du coup :)

**Comment by anatagawa** [comment]
merci bien, j'aimerai pas me passer d'un tres bon soft :)

**Comment by flozz** [comment]
Fixed in **v1.1.0**.

You can download it here for Windows → https://github.com/flozz/img2gb/releases/tag/v1.1.0 or update it with pip :)
